# Railway Nixpacks configuration (simpler than Docker)

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "cd packages/transcript-analyzer && npm install",
  "cd api-server && npm install"
]

[phases.build]
cmds = [
  "cd packages/transcript-analyzer && npm run build",
  "cd api-server && npm run build"
]

[start]
workingDir = "/app/api-server"
cmd = "node dist/index.js"
